export const apparel_list = [	"Activewear T Shirt",
					"Backpack",
					"Belt",
					"Blazer",
					"Blouse",
					"Boat Shoes",
					"Bodysuit",
					"Bomber Jacket",
					"Boot Cut Pants",
					"Boyfriend Pants",
					"Bra",
					"Bracelet",
					"Burmuda Shorts",
					"Button-Down",
					"Capris",
					"Cardigan",
					"Cargo Shorts",
					"Casual Dress",
					"Clogs",
					"Cocktail Dress",
					"Cross Body Bag",
					"Denim Jacket",
					"Dress",
					"Earring",
					"Flats",
					"Fleece Jacket",
					"Formal Dress",
					"Full Bikini",
					"Fur Coat",
					"Gloves",
					"Halter Top",
					"Hoodies",
					"Jean Skirt",
					"Jeans",
					"Jumpsuit",
					"Kimono",
					"Kimonos",
					"Knee Length Skirt",
					"Laptop Bag",
					"Leather Jacket",
					"Leggings",
					"Little Black Dress",
					"Loafers",
					"Maxi Dress",
					"Maxi Skirt",
					"Men's Boots",
					"Men's Dress Shoes",
					"Men's Hat",
					"Men's Sandals",
					"Men's Scarf",
					"Men's Shorts",
					"Men's Underwear",
					"Men's Watch",
					"Midi Skirt",
					"Mini Skirt",
					"Necklace",
					"One-Piece",
					"Overalls",
					"Oxfords",
					"Pant Suit",
					"Panties",
					"Peacoat",
					"Platform Shoes",
					"Polos",
					"Prom Dress",
					"Puffy Coat",
					"Pumps",
					"Raincoats",
					"Relaxed Pants",
					"Ring",
					"Robe",
					"Romper",
					"Sarong",
					"Satchel",
					"Skinny Pants",
					"Skirt",
					"Skirt Suit",
					"Sleepwear",
					"Sneakers",
					"Socks",
					"Sports Bra",
					"Spring Jacket",
					"Strapless Dress",
					"Sunglasses",
					"Sweater",
					"Sweatshirt",
					"Swimwear",
					"T-Shirt",
					"Tank Top",
					"Tankini",
					"Tie",
					"Tights",
					"Tote Bag",
					"Tracksuit",
					"Tube Top",
					"Tunic",
					"Turtleneck",
					"Umbrella",
					"Vest",
					"Wallet",
					"Wedding Dress",
					"Wide Leg Pants",
					"Women's Board Shorts",
					"Women's Boots",
					"Women's Hat",
					"Women's Jean Shorts",
					"Women's Sandals",
					"Women's Scarf",
					"Women's Short Shorts",
					"Women's Shorts",
					"Women's Watch",
					"Wristlet Clutch"]


export const apparel_tops = [
					"Activewear T Shirt",
					"Blazer",
					"Blouse",
					"Bra",
					"Button-Down",
					"Cardigan",
					"Casual Dress",
					"Cocktail Dress",
					"Fleece Jacket",
					"Formal Dress",
					"Fur Coat",
					"Halter Top",
					"Hoodies",
					"Leather Jacket",
					"Peacoat",
					"Polos",
					"Puffy Coat",
					"Raincoats",
					"Robe",
					"Romper",
					"Sports Bra",
					"Spring Jacket",
					"Strapless Dress",
					"Sweater",
					"Sweatshirt",
					"T-Shirt",
					"Tank Top",
					"Tankini",
					"Tunic",
					"Turtleneck",
					"Vest",
					"Wedding Dress",];

export const apparel_bottoms =[
					"Boot Cut Pants",
					"Boyfriend Pants",
					"Burmuda Shorts",
					"Capris",
					"Cargo Shorts",
					"Jeans",
					"Knee Length Skirt",
					"Leggings",
					"Little Black Dress",
					"Maxi Dress",
					"Maxi Skirt",
					"Men's Shorts",
					"Midi Skirt",
					"Mini Skirt",
					"Overalls",
					"Relaxed Pants",
					"Sarong",
					"Skinny Pants",
					"Skirt",
					"Skirt Suit",
					"Wide Leg Pants",
					"Women's Board Shorts",
					"Women's Jean Shorts",
					"Women's Short Shorts",
					"Women's Shorts",];

export const apparel_footwear = [
					"Boat Shoes",
					"Flats",
					"Men's Boots",
					"Men's Dress Shoes",
					"Men's Sandals",
					"Sneakers",
					"Women's Boots",
					"Women's Sandals",
];